### ISSUE TITLE
No module named 'compressed_rtf', How to solve this problem?

### ISSUE THREAD

**Issue by lveyis** [delimitry/compressed_rtf#16]
PS D:\xx\xx>**..\py3.11.9\python.exe -s -m pip install compressed-rtf==1.0.6**
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting compressed-rtf==1.0.6
  Using cached https://mirrors.aliyun.com/pypi/packages/8e/ac/abb196bb0b42a239d605fe97c314c3312374749013a07da4e6e0408f223c/compressed_rtf-1.0.6.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-ie18x_1n\compressed-rtf_b50f20ebc7414f198ba20cf6b362ebf9\setup.py", line 7, in <module>
          import compressed_rtf
      ModuleNotFoundError: No module named 'compressed_rtf'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by chenwei20** [comment]
PS D:\xx\xx> ..\py3.11.9\python.exe -s -m pip install compressed_rtf==1.0.6
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting compressed_rtf==1.0.6
  Using cached https://mirrors.aliyun.com/pypi/packages/8e/ac/abb196bb0b42a239d605fe97c314c3312374749013a07da4e6e0408f223c/compressed_rtf-1.0.6.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-5umuaofk\compressed-rtf_c06ec6e161dc430e8b1f3062504c2194\setup.py", line 7, in <module>
          import compressed_rtf
      ModuleNotFoundError: No module named 'compressed_rtf'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by chenwei20** [comment]
ok, I have solved this problem by compiling the whl file 
PS D:\openwebui\backend> ..\py3.11.9\python.exe -m pip install .\compressed_rtf-1.0.6-py3-none-any.whl
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Processing d:\openwebui\backend\compressed_rtf-1.0.6-py3-none-any.whl
Installing collected packages: compressed-rtf
Successfully installed compressed-rtf-1.0.6

**Comment by lveyis** [comment]
**ok, I have solved this problem by compiling the whl file**
PS D:\xx\xx> **..\py3.11.9\python.exe -m pip install .\compressed_rtf-1.0.6-py3-none-any.whl**
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Processing d:\openwebui\backend\compressed_rtf-1.0.6-py3-none-any.whl
Installing collected packages: compressed-rtf
Successfully installed compressed-rtf-1.0.6

**Comment by luan1223** [comment]
Now the.whl file is gone. How can it be resolved?
