### ISSUE TITLE
Decompression issues

### ISSUE THREAD

**Issue by spamv** [delimitry/compressed_rtf#2]
Hi,

I decompress an RTF object which it seems that works okay (no CRC error messages). But when I compress it again I don't get the same object. I've got the same Raw size but different Comp. size (lower than the original) and obviously different CRC.
Is there any know issue about it?

Thanks,

**Comment by TheElementalOfDestruction** [comment]
If you proceed to decompress it, compress it, then decompress the new compressed version does it come out the same?

Edit: I just tried it myself and it does. My guess is that the version of the algorithm (or just the compression level) is different by default than that of the original version. As both decompress the same, I do not see it currently as an issue, however I will look into it a bit further to see if _I_ can find a solution.

**Comment by TheElementalOfDestruction** [comment]
Well, it does actually seem to be an issue since it increased the size of one of my files by nearly 20%, so this should be looked into. I seriously wonder why that is.

**Comment by delimitry** [comment]
Hi, @spamv and @TheElementalOfCreation 

I've checked the specification https://msdn.microsoft.com/en-us/library/cc463890(v=exchg.80).aspx and 
here is the quote from it:
> ### 2.3.3.2.1 Finding the Longest Match to Input
> ...
> The algorithm computes the longest match in the dictionary of the current position within the input by
> using one of multiple implementation-dependent mechanisms. The following pseudocode is provided
> as one example; however, it is not necessary to follow this exactly, so long as the decompression
> algorithm specified in section 2.2 generates the original input given the compressed output generated.

I suppose that the implementation of finding the longest match, which was used in compression algorithm of @spamv's file, is differs from implementation currently used in the project.

**Comment by spamv** [comment]
@delimitry that could make sense. 
The object I'm using is directly created by MS, so I guess they might follow the specification.
I'll dig into it.
