### ISSUE TITLE
PyPI version is not up-to-date

### ISSUE THREAD

**Issue by fleetingbytes** [delimitry/compressed_rtf#6]
I installed compressed_rtf version 1.0.5 from PyPI and when I was trying to decompress it got hung around line 167:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\pit\lib\site-packages\compressed_rtf\compressed_rtf.py", line 167, in decompress
    output_buffer += bytes([char]) if PY3 else char
```

Having seen that you now have better code around that line, I uninstalled it and installed the version 1.0.5 from github. With that I could successfully decode the data. So github and PyPI are not offering the same version. Please count up the version number and update `compressed_rtf` on PyPI.

**Comment by delimitry** [comment]
New version is uploaded to PyPI. 
Thank you @Nagidal :+1:
