### ISSUE TITLE
CRC field not set to 0 when uncompressed

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [delimitry/compressed_rtf#9]
[MS-OXRTFCP] says the CRC field MUST be set to %x00.00.00.00 if the data is uncompressed (I can see it in the current version on page 10), but the compress function calculates it and sets it regardless of the compression setting.

**Comment by delimitry** [comment]
Thank you @TheElementalOfDestruction 👍🏻

**Comment by delimitry** [comment]
Merged into master
